#!/usr/bin/env python3
"""
backfill_prayers.py — one-time pass that converts existing GWM prayer lines
from instructional phrasing ("Pray for...", "Lift up...", "Ask God to...") to
bare situation phrases, regenerated by Claude for quality.

Updates BOTH layers, keyed by wp_id, so they stay in sync:
  - WordPress post body: the <p class="gwm-prayer-line"> paragraph, relabeled
    "Pray for:" with a bare situation phrase.
  - Active JSON feed (persecution.json / conflict.json / disasters.json):
    the per-event "prayer" field.

Run from /opt/conflict-pipeline (its .env has WP + Anthropic + GitHub creds):

    cd /opt/conflict-pipeline && set -a && source .env && set +a && \
      venv/bin/python backfill_prayers.py --dry-run          # preview, writes nothing
      venv/bin/python backfill_prayers.py                    # all three feeds
      venv/bin/python backfill_prayers.py --feed conflict    # one feed only
      venv/bin/python backfill_prayers.py --limit 20         # first 20 posts per feed

Resumable: completed post IDs are saved to data/backfill_prayers_done.json and
skipped on re-run. Safe to Ctrl-C and restart. Re-running after a clean finish
does nothing unless you delete that file.
"""
import os
import re
import sys
import json
import time
import base64
import argparse
import logging
import html
import requests
from datetime import datetime, timezone
from dotenv import load_dotenv
import anthropic

load_dotenv()

WP_URL          = os.environ['WP_URL'].rstrip('/')
WP_USER         = os.environ['WP_USER']
WP_APP_PASSWORD = os.environ['WP_APP_PASSWORD']
ANTHROPIC_KEY   = os.environ['ANTHROPIC_API_KEY']
GITHUB_TOKEN    = os.environ['GITHUB_TOKEN']
GITHUB_OWNER    = os.environ.get('GITHUB_OWNER', 'InnovativeGeospatial').strip()
GITHUB_REPO     = os.environ.get('GITHUB_REPO', 'GWM').strip()
GITHUB_BRANCH   = os.environ.get('GITHUB_BRANCH', 'main').strip()

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    datefmt='%H:%M:%S',
)
log = logging.getLogger(__name__)

FEEDS = {
    'persecution': {'cat': 7,  'json': 'persecution.json'},
    'conflict':    {'cat': 8,  'json': 'conflict.json'},
    'disaster':    {'cat': 38, 'json': 'disasters.json'},
}

DONE_FILE = '/opt/conflict-pipeline/data/backfill_prayers_done.json'

PRAYER_LINE_RE = re.compile(r'<p class="gwm-prayer-line">.*?</p>',
                            re.DOTALL | re.IGNORECASE)
META_DIV_RE = re.compile(r'<div class="gwm-(?:conflict-|disaster-)?meta".*?</div>',
                         re.DOTALL | re.IGNORECASE)
TAG_RE = re.compile(r'<[^>]+>')

# Leading words we never want a "situation phrase" to start with.
_LEADER_RE = re.compile(
    r'^(pray for|pray that|pray|lift up|ask god (?:to|for)|ask god|'
    r'we pray|may|let|grant|bring|protect|comfort|sustain|uphold|'
    r'intercede for|for)\s+',
    re.IGNORECASE,
)

client = anthropic.Anthropic(api_key=ANTHROPIC_KEY)

SYS = (
    "You rewrite a single prayer-list entry for a Christian news platform. "
    "Given a news report, output ONE bare situation phrase that names who is "
    "affected and what is happening -- the thing to pray for. It is NOT an "
    "instruction and NOT a sentence.\n\n"
    "RULES:\n"
    "- No leading verb. Never begin with Pray, Lift up, Ask God, May, Let, "
    "Grant, Bring, Protect, Comfort, or the word 'for'.\n"
    "- A noun phrase, not a full sentence. Do not end with a period unless it "
    "naturally needs one.\n"
    "- 8 to 25 words.\n"
    "- Name the country and the concrete need (people affected + circumstance).\n"
    "- No personal names; no specific church, town, village, or province names "
    "-- use the country only.\n"
    "- Do not assign political blame.\n\n"
    "Good: 'Two million civilians in Gaza facing ongoing airstrikes and "
    "worsening humanitarian conditions'\n"
    "Good: 'Families across Lebanon grieving and sheltering after deadly "
    "cross-border strikes'\n"
    "Bad: 'Pray for the families ...' (instruction)\n"
    "Bad: 'Lift up believers ...' (instruction)\n\n"
    "Respond with ONLY the phrase. No quotes, no label, no trailing commentary."
)


def regen_prayer(title, body_text):
    prompt = (
        "REPORT TITLE: " + (title or '') + "\n\n"
        "REPORT TEXT:\n" + (body_text or '')[:1600] + "\n\n"
        "Write the bare situation phrase now."
    )
    msg = client.messages.create(
        model='claude-sonnet-4-6',
        max_tokens=120,
        system=SYS,
        messages=[{'role': 'user', 'content': prompt}],
    )
    out = (msg.content[0].text or '').strip().strip('"\'').strip()
    # Safety net: strip any leading verb/instruction that slipped through.
    prev = None
    while prev != out:
        prev = out
        out = _LEADER_RE.sub('', out).strip()
    if out:
        out = out[0].upper() + out[1:]
    return out


def new_prayer_line(phrase):
    return ('<p class="gwm-prayer-line"><em>Pray for:</em> '
            + phrase + '</p>')


def body_to_text(raw):
    s = META_DIV_RE.sub(' ', raw or '')
    s = PRAYER_LINE_RE.sub(' ', s)
    s = TAG_RE.sub(' ', s)
    s = html.unescape(s)
    s = re.sub(r'\s+', ' ', s).strip()
    return s


def replace_or_insert_prayer(raw, line):
    if PRAYER_LINE_RE.search(raw):
        return PRAYER_LINE_RE.sub(line, raw, count=1)
    # No existing prayer line: insert before the first meta div if present
    # (meta is display:none and usually trails the body), else append.
    m = META_DIV_RE.search(raw)
    if m:
        return raw[:m.start()].rstrip() + '\n\n' + line + '\n\n' + raw[m.start():]
    return raw.rstrip() + '\n\n' + line


# ---- WordPress ----
def wp_iter_posts(cat, limit=None):
    auth = (WP_USER, WP_APP_PASSWORD)
    out = []
    page = 1
    while page <= 100:
        r = requests.get(
            WP_URL + '/wp-json/wp/v2/posts',
            params={
                'categories': cat,
                'per_page': 100,
                'page': page,
                'orderby': 'date',
                'order': 'desc',
                'context': 'edit',
                '_fields': 'id,title,content',
            },
            auth=auth, timeout=30,
        )
        if r.status_code == 400:
            break  # past last page
        if r.status_code != 200:
            log.warning('WP list failed (%s) page %d: %s',
                        r.status_code, page, r.text[:160])
            break
        batch = r.json()
        if not batch:
            break
        for p in batch:
            c = p.get('content') or {}
            t = p.get('title') or {}
            out.append({
                'id': p.get('id'),
                'title': (t.get('raw') or t.get('rendered') or ''),
                'raw': (c.get('raw') or c.get('rendered') or ''),
            })
            if limit and len(out) >= limit:
                return out
        page += 1
    return out


def wp_update_content(post_id, new_raw):
    auth = (WP_USER, WP_APP_PASSWORD)
    r = requests.post(
        WP_URL + '/wp-json/wp/v2/posts/' + str(post_id),
        json={'content': new_raw}, auth=auth, timeout=30,
    )
    return r.status_code in (200, 201)


# ---- GitHub feed update ----
def gh_headers():
    return {
        'Authorization': 'Bearer ' + GITHUB_TOKEN,
        'Accept': 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
    }


def gh_get_json(path):
    url = ('https://api.github.com/repos/' + GITHUB_OWNER + '/' + GITHUB_REPO
           + '/contents/' + path)
    r = requests.get(url, headers=gh_headers(),
                     params={'ref': GITHUB_BRANCH}, timeout=20)
    if r.status_code != 200:
        log.warning('GitHub GET %s -> %s', path, r.status_code)
        return None, None
    body = r.json()
    sha = body.get('sha')
    try:
        content = base64.b64decode(body.get('content', '')).decode('utf-8')
        return sha, json.loads(content)
    except Exception as e:
        log.warning('decode %s failed: %s', path, e)
        return sha, None


def gh_put_json(path, sha, data):
    url = ('https://api.github.com/repos/' + GITHUB_OWNER + '/' + GITHUB_REPO
           + '/contents/' + path)
    content = json.dumps(data, ensure_ascii=False, indent=2)
    payload = {
        'message': 'Backfill prayer phrasing ' +
                   datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC'),
        'content': base64.b64encode(content.encode('utf-8')).decode('ascii'),
        'branch': GITHUB_BRANCH,
    }
    if sha:
        payload['sha'] = sha
    r = requests.put(url, headers=gh_headers(), json=payload, timeout=30)
    if r.status_code in (200, 201):
        return True
    log.error('GitHub PUT %s failed (%s): %s', path, r.status_code, r.text[:200])
    return False


def purge_jsdelivr(filename):
    try:
        r = requests.get(
            'https://purge.jsdelivr.net/gh/' + GITHUB_OWNER + '/' + GITHUB_REPO
            + '@' + GITHUB_BRANCH + '/' + filename, timeout=20)
        log.info('jsDelivr purge %s -> %s', filename, r.status_code)
    except Exception as e:
        log.warning('jsDelivr purge failed for %s: %s', filename, e)


def update_feed_prayers(json_path, id_to_prayer, dry_run):
    if not id_to_prayer:
        return
    sha, data = gh_get_json(json_path)
    if not data or not isinstance(data.get('events'), list):
        log.warning('Feed %s missing/!events; skipping feed update', json_path)
        return
    changed = 0
    for ev in data['events']:
        wid = ev.get('wp_id')
        if wid in id_to_prayer:
            ev['prayer'] = id_to_prayer[wid]
            changed += 1
    log.info('Feed %s: %d/%d events updated', json_path, changed, len(data['events']))
    if dry_run:
        log.info('[dry-run] would PUT %s', json_path)
        return
    if changed and gh_put_json(json_path, sha, data):
        log.info('Feed %s written', json_path)
        purge_jsdelivr(json_path)


# ---- done-state ----
def load_done():
    try:
        with open(DONE_FILE) as f:
            return set(json.load(f))
    except Exception:
        return set()


def save_done(done):
    try:
        os.makedirs(os.path.dirname(DONE_FILE), exist_ok=True)
        with open(DONE_FILE, 'w') as f:
            json.dump(sorted(done), f)
    except Exception as e:
        log.warning('save done failed: %s', e)


def process_feed(name, cfg, args, done):
    log.info('=== Feed: %s (cat %s) ===', name, cfg['cat'])
    posts = wp_iter_posts(cfg['cat'], limit=args.limit)
    log.info('%s: %d posts to consider', name, len(posts))
    id_to_prayer = {}
    updated = 0
    for p in posts:
        pid = p['id']
        if pid in done:
            continue
        body_text = body_to_text(p['raw'])
        if len(body_text) < 40:
            log.info('  skip %s (body too thin)', pid)
            done.add(pid)
            continue
        try:
            phrase = regen_prayer(p['title'], body_text)
        except Exception as e:
            log.error('  regen failed for %s: %s', pid, e)
            continue
        if not phrase:
            log.info('  empty phrase for %s; leaving as-is', pid)
            done.add(pid)
            continue
        new_raw = replace_or_insert_prayer(p['raw'], new_prayer_line(phrase))
        if args.dry_run:
            log.info('  [dry-run] %s -> Pray for: %s', pid, phrase[:80])
            id_to_prayer[pid] = phrase
        else:
            if wp_update_content(pid, new_raw):
                id_to_prayer[pid] = phrase
                done.add(pid)
                updated += 1
                log.info('  %s -> Pray for: %s', pid, phrase[:80])
            else:
                log.error('  WP update failed for %s', pid)
            if updated % 10 == 0:
                save_done(done)
            time.sleep(1.2)
    save_done(done)
    update_feed_prayers(cfg['json'], id_to_prayer, args.dry_run)
    log.info('=== %s done: %d posts updated ===', name, updated)


def main():
    ap = argparse.ArgumentParser(description='Backfill GWM prayer phrasing')
    ap.add_argument('--feed', choices=list(FEEDS.keys()),
                    help='Only this feed (default: all three)')
    ap.add_argument('--limit', type=int, default=None,
                    help='Max posts per feed (for testing)')
    ap.add_argument('--dry-run', action='store_true',
                    help='Preview only; write nothing')
    args = ap.parse_args()

    done = load_done()
    log.info('Loaded %d previously-completed post IDs', len(done))

    feeds = [args.feed] if args.feed else list(FEEDS.keys())
    for name in feeds:
        process_feed(name, FEEDS[name], args, done)

    log.info('=== ALL DONE ===')


if __name__ == '__main__':
    main()
